In [1]:
import numpy as np
import pandas as pd
dataset=pd.read_csv("C:\\Users\\Arpit\\Desktop\\X Trimester\\IMLA\\Datasets\\dt.csv")

In [3]:
X=dataset.iloc[:,:-1]#feature
feature_cols=['age','income','student','credit_rating']
Y=dataset.iloc[:,4].values #classtables

from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()
X=X.apply(LabelEncoder().fit_transform)
from sklearn.tree import DecisionTreeClassifier
regressor=DecisionTreeClassifier(criterion='entropy',max_depth=5,splitter='best')
X

age  income  Student  credit_rating
0     1       0        0              1
1     1       0        0              0
2     0       0        0              1
3     2       2        0              1
4     2       1        1              1
5     2       1        1              0
6     0       1        1              0
7     1       2        0              1
8     1       1        1              1
9     2       2        1              1
10    1       2        1              0
11    0       2        0              0
12    0       0        1              1
13    2       2        0              0

In [5]:
regressor.fit(X,Y)
X_in=np.array([1,1,0,0])
y_pred=regressor.predict([X_in])
print("Prediction: ",y_pred)

Prediction:  ['no']


In [6]:
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
dot_data=StringIO()
export_graphviz(regressor,out_file=dot_data,filled=True,
               rounded=True,special_characters=True,feature_names=feature_cols,
               class_names=['0','1'])
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('tree.png')

C:\Users\Arpit\anaconda3\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


True

In [1]:
import numpy as np
import pandas as pd
dataset=pd.read_csv("C:\\Users\\Arpit\\Desktop\\X Trimester\\IMLA\\Datasets\\pima-indians-diabetes.csv")

In [2]:
X=dataset.iloc[:,:-1]#feature
feature_cols=['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigree','Age']
Y=dataset.iloc[:,8].values #classtables

from sklearn.preprocessing import LabelEncoder
labelencoder_X=LabelEncoder()
X=X.apply(LabelEncoder().fit_transform)
from sklearn.tree import DecisionTreeClassifier
regressor=DecisionTreeClassifier(criterion='entropy',max_depth=5,splitter='best')
X

6  148  72  35    0  33.6  0.627  50
0     1   23  19  22    0    62    196  10
1     8  121  17   0    0    30    367  11
2     1   27  19  16   62    77     53   0
3     0   75   4  28  102   209    513  12
4     5   54  23   0    0    53     80   9
..   ..  ...  ..  ..  ...   ...    ...  ..
762  10   39  25  41  108   118     55  42
763   2   60  21  20    0   155    187   6
764   5   59  22  16   71    58    115   9
765   1   64  14   0    0    95    195  26
766   1   31  21  24    0    98    169   2

[767 rows x 8 columns]

In [3]:
regressor.fit(X,Y)
X_in=np.array([1,1,1,1,0,0,0,0])
y_pred=regressor.predict([X_in])
print("Prediction: ",y_pred)

Prediction:  [0]


In [4]:
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
dot_data=StringIO()
export_graphviz(regressor,out_file=dot_data,filled=True,
               rounded=True,special_characters=True,feature_names=feature_cols,
               class_names=['0','1'])
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('diabetes.png')

C:\Users\Arpit\anaconda3\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


True

In [5]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_squared_error

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv("C:\\Users\\Arpit\\Desktop\\X Trimester\\IMLA\\Datasets\\linear data.csv")

In [7]:
X=data.iloc[:,:-1].values #feature
y=data.iloc[:,-1].values #target

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.50,random_state=0)

In [9]:
drm=DecisionTreeRegressor()

In [10]:
drm.fit(x_train,y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [11]:
y_pred=drm.predict(X)

In [12]:
y_pred

array([70., 70., 70., 50., 70., 98., 70., 98.])

In [13]:
mse=mean_squared_error(y,y_pred)
mse

749.875

In [14]:
rmse=np.sqrt(mse)
rmse

27.383845602836722

In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [18]:
y_prediction=classifier.predict(X)

In [19]:
y_prediction

array([45, 45, 45, 50, 45, 98, 45, 98], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, y_pred)
print(cm)
accuracy_score(y, y_pred)

[[0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]]


0.25